
node {

 checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
        dir ('Test') {
          bat 'mvn clean'
            bat 'mvn package'
       def customImage = docker.build("simhalp9/micro")

        /* Push the container to the custom Registry */
      customImage.push()
    }
}
}




