apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 31233
  selector:
    app: payment
  
